/**
 * Forge migrate — S04/T01: e2e proof that a migrated real forge-agent 1.0
 * fixture flows through the REAL `runForgeLoop` (`once: false` — the actual
 * `/forge auto` code path, NOT `/forge next`'s `once: true`) to a genuine
 * `LoopTerminal.reason === "complete"` terminal.
 *
 * S03's `migrate-resume.test.ts` proves `deriveNextUnit` derives the right
 * unit from migrated data but never calls the loop itself. This test closes
 * that gap: it duplicates (does not import) the same `task-pending`
 * mid-flight fixture setup migrate-resume.test.ts uses (that helper is
 * file-local/unexported), then drives the loop with an adaptive fake
 * `SessionDriver` — mirroring `loop.test.ts`'s `completionSteps()` pattern —
 * until the loop itself reports completion.
 *
 * Same copy-only / never-mutate-the-source discipline as S01-S03's
 * real-fixture suites: `M002_DIR` is only ever read via `cpSync`, and the
 * sandbox is always cleaned up in a `finally`.
 */

import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync, cpSync, unlinkSync } from "node:fs";
import { tmpdir, homedir } from "node:os";
import { join } from "node:path";
import { applyMigration } from "../migrate/apply.ts";
import { runForgeLoop, type SessionDriver } from "../auto/loop.ts";
import { ForgeAutoSession } from "../auto/session.ts";
import { readState } from "../state/store.ts";
import type { NextUnit } from "../state/dispatch.ts";
import { unitSlice } from "../state/dispatch.ts";
import type { UnitOutcome } from "../worker/rendezvous.ts";

const FORGE_AGENT_ROOT = join(homedir(), "Documents", "dev", "forge-agent");
const M002_DIR = join(FORGE_AGENT_ROOT, ".gsd", "milestones", "M002");
const FORGE_AGENT_SKIP =
  "~/Documents/dev/forge-agent não existe nesta máquina — projeto 1.0 separado, " +
  "fixture só disponível no workspace de desenvolvimento que o tem clonado";

const DASHBOARD_1X = [
  "<!-- AUTO-GENERATED by scripts/forge-dashboard.js — do not edit by hand -->",
  "",
  "# GSD Dashboard",
  "",
  "No active runs.",
  "",
].join("\n");

/**
 * Reproduces (duplicated, not imported — `migrate-resume.test.ts`'s helper is
 * file-local) the exact `task-pending` mid-flight scenario: copy the real
 * M002 fixture into an isolated sandbox, flip `M002-STATE.md` complete→active
 * and `S01/T01/T01-PLAN.md` DONE→RUNNING, and delete `T01-SUMMARY.md`.
 *
 * ONE extra flip beyond `migrate-resume.test.ts`'s scenario: the real
 * `M002-STATE.md` also carries a separate `**Phase:** complete` prose line
 * (distinct from the `status:` frontmatter field), which `applyStateConversion`
 * copies verbatim into the converted 2.0 `phase:` field. `migrate-resume.test.ts`
 * never needed to flip it because its assertions stop at `deriveNextUnit`,
 * which does not consult `phase` — but this task drives the REAL loop, whose
 * `reconcileCompletion`/`milestoneComplete` DO gate on `phase === "complete"`.
 * Left unflipped, the converted STATE.md would read `phase: complete` despite
 * S01/T01 being reverted to running, short-circuiting `milestoneComplete()`
 * to `true` and making the loop falsely treat the milestone as already closed.
 */
function setupTaskPendingFixture(): string {
  const dir = mkdtempSync(join(tmpdir(), "forge-migrate-e2e-auto-test-"));

  mkdirSync(join(dir, ".gsd"), { recursive: true });
  writeFileSync(join(dir, ".gsd", "STATE.md"), DASHBOARD_1X, "utf-8");

  const destMilestonesDir = join(dir, ".gsd", "milestones");
  mkdirSync(destMilestonesDir, { recursive: true });
  const destM002 = join(destMilestonesDir, "M002");
  cpSync(M002_DIR, destM002, { recursive: true });

  const m002StatePath = join(destM002, "M002-STATE.md");
  const m002StateRaw = readFileSync(m002StatePath, "utf-8");
  assert.match(m002StateRaw, /^status:\s*complete\s*$/m, "fixture assumption: real M002-STATE.md status is complete");
  assert.match(m002StateRaw, /^\*\*Phase:\*\*\s*complete\s*$/m, "fixture assumption: real M002-STATE.md Phase is complete");
  const m002StateFlipped = m002StateRaw
    .replace(/^status:\s*complete\s*$/m, "status: active")
    .replace(/^\*\*Phase:\*\*\s*complete\s*$/m, "**Phase:** active");
  writeFileSync(m002StatePath, m002StateFlipped, "utf-8");

  const t01Dir = join(destM002, "slices", "S01", "tasks", "T01");
  const t01Plan = join(t01Dir, "T01-PLAN.md");
  const t01Summary = join(t01Dir, "T01-SUMMARY.md");
  assert.ok(existsSync(t01Plan) && existsSync(t01Summary), "fixture assumption: S01/T01 has PLAN+SUMMARY");
  const planRaw = readFileSync(t01Plan, "utf-8");
  assert.match(planRaw, /^status:\s*DONE\s*$/m);
  writeFileSync(t01Plan, planRaw.replace(/^status:\s*DONE\s*$/m, "status: RUNNING"), "utf-8");
  unlinkSync(t01Summary);

  return dir;
}

/** Reuses `loop.test.ts`'s JSONL parse pattern for `.gsd/forge/events.jsonl`. */
function readEvents(cwd: string): Array<Record<string, unknown>> {
  const path = join(cwd, ".gsd", "forge", "events.jsonl");
  if (!existsSync(path)) return [];
  return readFileSync(path, "utf-8")
    .split("\n")
    .filter((l) => l.trim().length > 0)
    .map((l) => JSON.parse(l) as Record<string, unknown>);
}

function done(summary: string): UnitOutcome {
  return { kind: "result", result: { status: "done", summary, artifacts: [] } };
}

describe(
  "migrate-e2e-auto — migrated real M002 fixture flows through the real runForgeLoop (once:false)",
  { skip: !existsSync(M002_DIR) && FORGE_AGENT_SKIP },
  () => {
    test("task-pending fixture: real applyMigration + real runForgeLoop reach LoopTerminal.reason === 'complete'", async () => {
      const dir = setupTaskPendingFixture();
      try {
        const report = applyMigration(dir);
        assert.equal(report.state.milestoneId, "M002", "applyMigration must resolve M002 as the active milestone");
        assert.equal(report.units.written, true);

        const milestoneDir = join(dir, ".gsd", "milestones", "M002");
        const units: NextUnit[] = [];

        // Adaptive fake driver: the exact remaining dispatch count after T01 is
        // NOT hardcoded — it depends on what's genuinely still incomplete on the
        // real M002 fixture. `plan-slice` should never appear on this fixture
        // (S01-S03 already provide every PLAN); fail loudly if it ever does.
        const driver: SessionDriver = {
          async dispatch(unit: NextUnit): Promise<UnitOutcome> {
            units.push(unit);
            if (unit.type === "execute-task") {
              assert.deepEqual(unit, { type: "execute-task", slice: "S01", task: "T01" });
              return done("t01 done via e2e");
            }
            if (unit.type === "complete-slice") {
              writeFileSync(
                join(milestoneDir, "slices", unitSlice(unit), `${unitSlice(unit)}-SUMMARY.md`),
                `# ${unitSlice(unit)} summary\n`,
              );
              return done("slice summary written");
            }
            if (unit.type === "complete-milestone") {
              writeFileSync(join(milestoneDir, "M002-SUMMARY.md"), "# M002 summary\n");
              return done("milestone summary written");
            }
            assert.fail(`unexpected unit type on the real M002 fixture: ${JSON.stringify(unit)}`);
          },
        };

        const session = new ForgeAutoSession();
        session.active = true;
        session.cwd = dir;

        const terminal = await runForgeLoop(session, { cwd: dir, driver }, { once: false });

        assert.equal(terminal.reason, "complete", "the real loop must reach a genuine complete terminal");
        assert.deepEqual(
          units[0],
          { type: "execute-task", slice: "S01", task: "T01" },
          "the first dispatched unit must be the reverted S01/T01 task",
        );

        const state = readState(dir);
        assert.ok(
          state.units?.some((u) => u.type === "task" && u.id === "T01" && u.status === "done"),
          "T01 must be persisted as done in STATE after the run",
        );

        const kinds = readEvents(dir).map((e) => e.kind);
        assert.ok(kinds.includes("unit_dispatched"), "the journal must record at least one unit_dispatched event");
        assert.ok(kinds.includes("unit_result"), "the journal must record at least one unit_result event");
        const events = readEvents(dir);
        assert.ok(
          events.some((e) => e.kind === "unit_dispatched" && e.unit === "S01/T01"),
          "a unit_dispatched event for S01/T01 must be journaled",
        );
        assert.ok(
          events.some((e) => e.kind === "unit_result" && e.unit === "S01/T01"),
          "a unit_result event for S01/T01 must be journaled",
        );
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    });
  },
);
