/**
 * Forge migrate — coverage for `buildMigrateReport`/`formatMigrateReport`
 * (T04, `migrate/report.ts`) and the `/forge migrate` subcommand's zero-write
 * guarantee.
 *
 * Same one-shot-copy / mkdtemp-sandbox discipline as
 * `migrate-state-layout.test.ts` (T01) — nothing here mutates a real
 * project's `.gsd/` tree.
 *
 * The full `case "migrate":` handler in `commands/forge-command.ts` needs a
 * real `ExtensionCommandContext`, which this slice's tests avoid building
 * from scratch (see `forge-command.test.ts`'s own `fakeCtx` for the closest
 * precedent). Per T04-PLAN Step 6, the zero-write proof below exercises the
 * REAL I/O path directly — `buildMigrateReport` + `formatMigrateReport` — and
 * the subcommand routing is instead asserted structurally against the
 * source text of `forge-command.ts`.
 */

import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { buildMigrateReport, formatMigrateReport, type MigrateReport } from "../migrate/report.ts";

function withSandbox<T>(fn: (dir: string) => T): T {
  const dir = mkdtempSync(join(tmpdir(), "forge-migrate-command-test-"));
  try {
    return fn(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// ── buildMigrateReport — empty sandbox ───────────────────────────────────────

describe("buildMigrateReport — empty sandbox (no .gsd/ at all)", () => {
  test("never throws and every cwd-scoped field degrades to empty/absent", () => {
    withSandbox((dir) => {
      let report: MigrateReport | undefined;
      assert.doesNotThrow(() => {
        report = buildMigrateReport(dir);
      });

      assert.equal(report!.stateTop.kind, "absent");
      assert.deepEqual(report!.milestoneStates, []);
      // `prefs` reuses `prefsSources(cwd)` (T02), which includes two layers
      // anchored to the REAL home directory (`~/.claude/forge-agent-prefs.md`,
      // `gsdHome()/prefs.md`) that are not sandboxable by passing a fake cwd —
      // see the same caveat documented in migrate-prefs-layout.test.ts (T01/T02).
      // Only the cwd-anchored "repo"/"local" layers are guaranteed absent here.
      const cwdScopedPrefs = report!.prefs.filter((p) => p.source.startsWith(dir));
      assert.deepEqual(cwdScopedPrefs, []);
      assert.equal(report!.fragmentStores.length, 3);
      for (const store of report!.fragmentStores) {
        assert.deepEqual(store.files, []);
      }
      assert.deepEqual(report!.orphans, []);
      assert.deepEqual(report!.roadmap, []);
    });
  });

  test("formatMigrateReport on the degraded empty report still produces the dry-run line, never throws", () => {
    withSandbox((dir) => {
      const report = buildMigrateReport(dir);
      let text = "";
      assert.doesNotThrow(() => {
        text = formatMigrateReport(report);
      });
      assert.match(text, /Nenhuma escrita foi realizada \(dry-run\)/);
    });
  });
});

// ── formatMigrateReport — synthetic MigrateReport fixture ──────────────────

describe("formatMigrateReport — synthetic fixture", () => {
  const syntheticReport: MigrateReport = {
    stateTop: {
      kind: "dashboard1x",
      path: "/tmp/fixture/.gsd/STATE.md",
      detail: "comentário HTML AUTO-GENERATED by scripts/forge-dashboard.js (dashboard forge 1.0)",
    },
    milestoneStates: [
      {
        kind: "frontmatter1x",
        path: "/tmp/fixture/.gsd/milestones/M999/M999-STATE.md",
        detail: "frontmatter --- + **Active Slice:** no corpo (per-milestone STATE forge 1.0)",
      },
    ],
    prefs: [
      {
        source: "/tmp/fixture/forge-agent-prefs.md",
        label: "legacy ~/.claude",
        shape: "nested1x",
        unmapped: ["review", "plan_gate"],
      },
    ],
    fragmentStores: [
      {
        store: "decisions",
        dir: "/tmp/fixture/.gsd/decisions",
        files: [
          { path: "/tmp/fixture/.gsd/decisions/M001.md", compatible: false, detail: "shape 1.0 detectado" },
          { path: "/tmp/fixture/.gsd/decisions/M002.md", compatible: true, detail: "shape 2.0 nativo" },
        ],
      },
      { store: "ledger", dir: "/tmp/fixture/.gsd/ledger", files: [] },
      { store: "memory", dir: "/tmp/fixture/.gsd/memory", files: [] },
    ],
    orphans: [{ path: "/tmp/fixture/.gsd/milestones/S03", reason: "diretório não reconhecível" }],
    roadmap: [
      {
        kind: "prose1x",
        path: "/tmp/fixture/.gsd/milestones/M999/M999-ROADMAP.md",
        detail:
          'seção "## Slices" em prosa+checkbox `- [ ]/[x] **S##: Título** `risk:X` `depends:[...]`` (formato forge 1.0)',
      },
    ],
  };

  test("contains the dry-run disclaimer line", () => {
    const text = formatMigrateReport(syntheticReport);
    assert.match(text, /Nenhuma escrita foi realizada \(dry-run\)\. --apply chega no S02\./);
  });

  test("mentions at least one finding from each of the 6 dimensions", () => {
    const text = formatMigrateReport(syntheticReport);
    assert.match(text, /dashboard forge 1\.0/, "STATE.md topo");
    assert.match(text, /M999-STATE\.md/, "STATE.md per-milestone");
    assert.match(text, /review, plan_gate/, "prefs unmapped keys, listed explicitly");
    assert.match(text, /decisions.*1\/2 arquivo\(s\) incompatível/, "fragment-store incompatibility count");
    assert.match(text, /S03/, "orphan artifact");
    assert.match(text, /M999-ROADMAP\.md/, "roadmap (6th dimension) — prose1x milestone");
  });
});

// ── Zero-write proof: buildMigrateReport + formatMigrateReport over a mixed .gsd/ fixture ──

function snapshotTree(root: string): string[] {
  const out: string[] = [];
  function walk(dir: string): void {
    for (const name of readdirSync(dir).sort()) {
      const full = join(dir, name);
      const st = statSync(full);
      if (st.isDirectory()) {
        walk(full);
      } else {
        out.push(`${full}:${st.size}:${readFileSync(full, "utf-8")}`);
      }
    }
  }
  walk(root);
  return out;
}

function writeMixedGsdFixture(cwd: string): void {
  // STATE.md dashboard 1.0 sintético
  const gsdDir = join(cwd, ".gsd");
  mkdirSync(gsdDir, { recursive: true });
  writeFileSync(
    join(gsdDir, "STATE.md"),
    [
      "<!-- AUTO-GENERATED by scripts/forge-dashboard.js — do not edit by hand -->",
      "",
      "# GSD Dashboard",
      "",
      "No active runs.",
      "",
    ].join("\n"),
  );

  // prefs.md nested1x sintético — repo layer (`<cwd>/.gsd/prefs.md`, per
  // `prefs.ts:prefsSources`), so `classifyPrefsLayout` actually picks it up.
  writeFileSync(
    join(gsdDir, "prefs.md"),
    [
      "# Forge Agent — prefs",
      "",
      "## Phase → Agent Routing",
      "",
      "| Phase | Agent |",
      "|-------|-------|",
      "| plan  | opus  |",
      "",
    ].join("\n"),
  );

  // decisions/ com um fragment 1.0-shaped
  const decisionsDir = join(gsdDir, "decisions");
  mkdirSync(decisionsDir, { recursive: true });
  writeFileSync(
    join(decisionsDir, "M001.md"),
    [
      "---",
      "unit_id: M001",
      "decisions:",
      "  - when: 2026-01-01",
      "    scope: teste",
      "    decision: algo",
      "    choice: A",
      "    rationale: porque sim",
      "    revisable: true",
      "---",
      "",
    ].join("\n"),
  );

  // Per-milestone prose+checkbox 1.0 ROADMAP.md — exercises the 6th dimension
  // (roadmap) in the same zero-write proof as the other 5.
  const milestoneDir = join(gsdDir, "milestones", "M100");
  mkdirSync(milestoneDir, { recursive: true });
  writeFileSync(
    join(milestoneDir, "M100-ROADMAP.md"),
    [
      "# M100 ROADMAP",
      "",
      "## Slices",
      "",
      "- [ ] **S01: Slice um** `risk:low` `depends:[]`",
      "",
    ].join("\n"),
  );
}

describe("zero-write proof — buildMigrateReport + formatMigrateReport over a mixed forge 1.0 fixture", () => {
  test("nenhum arquivo sob .gsd/ é criado, apagado ou modificado durante a chamada", () => {
    withSandbox((dir) => {
      writeMixedGsdFixture(dir);
      const before = snapshotTree(join(dir, ".gsd"));

      const report = buildMigrateReport(dir);
      const text = formatMigrateReport(report);

      const after = snapshotTree(join(dir, ".gsd"));
      assert.deepEqual(after, before, ".gsd/ tree must be byte-identical before and after the dry-run call");

      // Sanity: the fixture was actually classified as forge 1.0 shapes (not
      // silently skipped), so the zero-write assertion above is meaningful.
      assert.equal(report.stateTop.kind, "dashboard1x");
      assert.match(text, /dashboard forge 1\.0/);
      assert.equal(report.roadmap.length, 1);
      assert.equal(report.roadmap[0].kind, "prose1x");
      assert.match(text, /M100-ROADMAP\.md/, "roadmap (6th dimension) reported in the dry-run text");
    });
  });
});

// ── Subcommand routing — structural assertion over forge-command.ts source ──
//
// Per T04-PLAN Step 6: building a full ExtensionCommandContext mock just to
// cover one trivial routing line is not worth the fragility. Instead, assert
// structurally that `case "migrate":` exists, is wired to
// buildMigrateReport/formatMigrateReport via ctx.ui.notify, and never touches
// newSession/updateState/writeFileSync.

describe("/forge migrate — subcommand routing (structural)", () => {
  const source = readFileSync(
    new URL("../commands/forge-command.ts", import.meta.url),
    "utf-8",
  );

  test("'migrate' is registered in SUBCOMMANDS", () => {
    assert.match(source, /SUBCOMMANDS\s*=\s*\[[^\]]*"migrate"[^\]]*\]/);
  });

  test("case \"migrate\" renders the report to stdout (print/headless) or ctx.ui.notify (TUI), zero writes", () => {
    // External-review fix 5b506474: notify is a TUI surface, MUTE in --print —
    // the PRIMARY consumer of a dry-run. The case now branches on
    // isPrintHeadlessContext: stdout for headless, notify for the TUI.
    //
    // S02/T06: the case now ALSO contains an `if (rest[0] === "--apply")`
    // branch that legitimately mentions applyMigration/updateState-adjacent
    // strings — so the zero-write proof below is scoped to ONLY the `else`
    // sub-block (the dry-run path), not the whole case body.
    const caseMatch = source.match(/case "migrate": \{\s*\n([\s\S]*?)\n\s*\}\s*\n\s*case "(?:review|accounts|models|unblock)"/);
    assert.ok(caseMatch, "expected a case \"migrate\": { … } block before case \"unblock\"");
    const body = caseMatch![1];
    assert.doesNotMatch(body, /newSession/, "migrate must never reach ctx.newSession — dry-run or --apply, zero-write guarantee");

    const elseMatch = body.match(/\}\s*else\s*\{\s*\n([\s\S]*?)\n\s*\}\s*\n\s*return;/);
    assert.ok(elseMatch, "expected an `} else { … }` dry-run sub-block before the case's final return");
    const dryRunBody = elseMatch![1];

    assert.match(dryRunBody, /isPrintHeadlessContext\(ctx\)/);
    assert.match(dryRunBody, /process\.stdout\.write\(/);
    assert.match(dryRunBody, /ctx\.ui\.notify\(/);
    assert.match(dryRunBody, /formatMigrateReport\(/);
    assert.match(dryRunBody, /buildMigrateReport\(ctx\.cwd\)/);
    assert.doesNotMatch(dryRunBody, /newSession/, "migrate dry-run must never reach ctx.newSession — zero-write guarantee");
    assert.doesNotMatch(dryRunBody, /updateState/, "migrate dry-run must never call state/store.ts:updateState");
    assert.doesNotMatch(dryRunBody, /writeFileSync/, "migrate dry-run must never write to disk directly");
    assert.doesNotMatch(dryRunBody, /applyMigration/, "migrate dry-run must never call applyMigration");
    assert.doesNotMatch(dryRunBody, /backupGsdTree/, "migrate dry-run must never call backupGsdTree");
  });

  test("case \"migrate\" --apply sub-block calls applyMigration/formatApplyReport", () => {
    const caseMatch = source.match(/case "migrate": \{\s*\n([\s\S]*?)\n\s*\}\s*\n\s*case "(?:review|accounts|models|unblock)"/);
    assert.ok(caseMatch, "expected a case \"migrate\": { … } block before case \"unblock\"");
    const body = caseMatch![1];

    const applyMatch = body.match(/if \(rest\[0\] === "--apply"\) \{\s*\n([\s\S]*?)\n\s*\}\s*else\s*\{/);
    assert.ok(applyMatch, "expected an `if (rest[0] === \"--apply\") { … } else { … }` sub-block");
    const applyBody = applyMatch![1];

    assert.match(applyBody, /applyMigration\(/);
    assert.match(applyBody, /formatApplyReport\(/);
    assert.match(applyBody, /isPrintHeadlessContext\(ctx\)/);
  });

  test("formatHelp() lists 'migrate' with a descriptive line", () => {
    assert.match(source, /"\s*migrate\s*—[^"]*dry-run[^"]*"/);
  });
});
