/**
 * Forge migrate — S03/T05: end-to-end resume proof.
 *
 * Feeds a mid-flight-derived-from-real `M002` fixture through `applyMigration`
 * (T04) and then the REAL `deriveNextUnit` (`state/dispatch.ts`, imported with
 * ZERO modification) via the REAL `readSnapshot` (`auto/snapshot.ts` — the
 * exact same disk→memory assembly `/forge auto` itself uses to build
 * `PlansBySlice`/`CompletionInfo`, reused here rather than hand-rolled, per
 * the module's own docstring: "the pure heart of the S03 orchestration loop").
 * This proves that the DATA S01-S04 produce actually satisfies the
 * dispatcher's real contract, not a test-only substitute.
 *
 * No fixture 1.0 genuinely "mid-flight" exists in the available projects
 * (S03-PLAN.md §Notes) — `M002` (forge-agent 1.0, real, COMPLETE) is copied
 * and artificially reverted per scenario, preserving 100% real format/syntax.
 * Same one-shot-copy / skip-honest discipline as the rest of S01-S03's
 * real-fixture suites: the original `M002` dir is only ever read via `cpSync`
 * (source side of a copy) — never opened in write mode, never mutated. Every
 * subsequent edit targets the `mkdtemp` sandbox copy only.
 *
 * A necessary fixture-setup step applies to ALL THREE scenarios, not just
 * one: the real `M002-STATE.md` says `status: complete` (verified live —
 * `migrate-state-convert.test.ts`'s own real-fixture case asserts exactly
 * this), so `computeStateConversion` would otherwise never resolve M002 as
 * the active "winner" milestone at all, and `applyMigration` would skip
 * `applyUnitsConversion`/`applyRoadmapConversion` entirely — proving nothing.
 * `setupMidFlightFixture` flips that one field to a non-terminal status
 * before applying each scenario's own reversion.
 */

import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync, cpSync, unlinkSync } from "node:fs";
import { tmpdir, homedir } from "node:os";
import { join } from "node:path";
import { applyMigration } from "../migrate/apply.ts";
import { readSnapshot } from "../auto/snapshot.ts";
import { deriveNextUnit, type NextUnit } from "../state/dispatch.ts";

const FORGE_AGENT_ROOT = join(homedir(), "Documents", "dev", "forge-agent");
const M002_DIR = join(FORGE_AGENT_ROOT, ".gsd", "milestones", "M002");
const FORGE_AGENT_SKIP =
  "~/Documents/dev/forge-agent não existe nesta máquina — projeto 1.0 separado, " +
  "fixture só disponível no workspace de desenvolvimento que o tem clonado";

const DASHBOARD_1X = [
  "<!-- AUTO-GENERATED by scripts/forge-dashboard.js — do not edit by hand -->",
  "",
  "# GSD Dashboard",
  "",
  "No active runs.",
  "",
].join("\n");

type Scenario = "task-pending" | "slice-summary-missing" | "milestone-complete";

/**
 * Copy the real `M002` fixture into an isolated `mkdtemp` sandbox and apply
 * the scenario's specific reversion. Returns the sandbox dir (caller owns
 * cleanup via `rmSync`).
 */
function setupMidFlightFixture(scenario: Scenario): string {
  const dir = mkdtempSync(join(tmpdir(), "forge-migrate-resume-test-"));

  mkdirSync(join(dir, ".gsd"), { recursive: true });
  writeFileSync(join(dir, ".gsd", "STATE.md"), DASHBOARD_1X, "utf-8");

  const destMilestonesDir = join(dir, ".gsd", "milestones");
  mkdirSync(destMilestonesDir, { recursive: true });
  const destM002 = join(destMilestonesDir, "M002");
  cpSync(M002_DIR, destM002, { recursive: true });

  const m002StatePath = join(destM002, "M002-STATE.md");
  const m002StateRaw = readFileSync(m002StatePath, "utf-8");
  assert.match(m002StateRaw, /^status:\s*complete\s*$/m, "fixture assumption: real M002-STATE.md status is complete");
  writeFileSync(m002StatePath, m002StateRaw.replace(/^status:\s*complete\s*$/m, "status: active"), "utf-8");

  if (scenario === "task-pending") {
    // S01/T01 is real (status: DONE + T01-SUMMARY.md) — revert it to a
    // non-terminal status and remove its SUMMARY, simulating a task still in
    // flight in the middle of an otherwise-progressing slice (S01 has 3
    // tasks; T02/T03 stay untouched, i.e. genuinely done).
    const t01Dir = join(destM002, "slices", "S01", "tasks", "T01");
    const t01Plan = join(t01Dir, "T01-PLAN.md");
    const t01Summary = join(t01Dir, "T01-SUMMARY.md");
    assert.ok(existsSync(t01Plan) && existsSync(t01Summary), "fixture assumption: S01/T01 has PLAN+SUMMARY");
    const planRaw = readFileSync(t01Plan, "utf-8");
    assert.match(planRaw, /^status:\s*DONE\s*$/m);
    writeFileSync(t01Plan, planRaw.replace(/^status:\s*DONE\s*$/m, "status: RUNNING"), "utf-8");
    unlinkSync(t01Summary);
  } else if (scenario === "slice-summary-missing") {
    // S02 (single task T01, real status:DONE + SUMMARY, left untouched) —
    // remove only its S02-SUMMARY.md. The 1.0 checkbox for S02 stays [x]:
    // units-convert.ts's fail-safe (checkbox AND task-completeness AND
    // S##-SUMMARY.md existence) must downgrade the STATE unit to "pending" on
    // its own, and roadmap-convert.ts's converted pipe-table row must agree
    // (both now go through the same `computeSliceStatus`, see units-convert.ts).
    const s02Summary = join(destM002, "slices", "S02", "S02-SUMMARY.md");
    assert.ok(existsSync(s02Summary), "fixture assumption: S02-SUMMARY.md exists");
    unlinkSync(s02Summary);
  }
  // scenario === "milestone-complete": no reversion — M002 as-is (bar the
  // STATE status flip above, which only affects milestone-active
  // resolution, not slice/task completeness).

  return dir;
}

/** Negative assertion #1 (S03's founding risk): never a false-complete. */
function assertNeverFalseComplete(next: NextUnit | null, message: string): void {
  assert.notEqual(next, null, message);
}

/**
 * Negative assertion #2 (S03's founding risk): never a re-execution — an
 * `execute-task` result must never point at a task whose `T##-SUMMARY.md`
 * genuinely already exists on disk.
 */
function assertNeverReExecutesADoneTask(dir: string, milestoneId: string, next: NextUnit | null): void {
  if (next?.type !== "execute-task") return;
  const summaryPath = join(
    dir,
    ".gsd",
    "milestones",
    milestoneId,
    "slices",
    next.slice,
    "tasks",
    next.task,
    `${next.task}-SUMMARY.md`,
  );
  assert.equal(
    existsSync(summaryPath),
    false,
    `execute-task must never point at ${next.slice}/${next.task} whose SUMMARY already exists on disk (re-execution)`,
  );
}

describe(
  "migrate-resume — end-to-end resume proof (real M002-derived mid-flight fixture)",
  { skip: !existsSync(M002_DIR) && FORGE_AGENT_SKIP },
  () => {
    test("scenario 1 — pending task mid-slice: deriveNextUnit dispatches execute-task on the reverted task", () => {
      const dir = setupMidFlightFixture("task-pending");
      try {
        const report = applyMigration(dir);
        assert.equal(report.state.milestoneId, "M002", "applyMigration must resolve M002 as the active milestone");
        assert.equal(report.roadmap.written, true);
        assert.equal(report.units.written, true);

        const snap = readSnapshot(dir);
        assert.equal(snap.plans["S01"]?.tasks.find((t) => t.id === "T01")?.status, "running");

        const next = deriveNextUnit(snap.state, snap.roadmap, snap.plans, {
          milestoneSummaryWritten: snap.milestoneSummaryWritten,
        });

        assertNeverFalseComplete(next, "S01/T01 has genuinely pending work — deriveNextUnit must not report null");
        assertNeverReExecutesADoneTask(dir, "M002", next);
        assert.deepEqual(next, { type: "execute-task", slice: "S01", task: "T01" });
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    });

    test("scenario 2 — slice all-tasks-done but S##-SUMMARY.md missing: deriveNextUnit dispatches complete-slice", () => {
      const dir = setupMidFlightFixture("slice-summary-missing");
      try {
        const report = applyMigration(dir);
        assert.equal(report.state.milestoneId, "M002");

        const snap = readSnapshot(dir);
        // plans["S02"].summaryWritten is computed by the real readSnapshot
        // from actual disk state (existsSync), not hardcoded by this test.
        assert.equal(snap.plans["S02"]?.summaryWritten, false);
        assert.ok(snap.plans["S02"]?.tasks.every((t) => t.status === "done"), "S02's own task(s) must remain done");

        const next = deriveNextUnit(snap.state, snap.roadmap, snap.plans, {
          milestoneSummaryWritten: snap.milestoneSummaryWritten,
        });

        assertNeverFalseComplete(
          next,
          "S02's tasks are done but its SUMMARY artifact is still owed — must not report null",
        );
        assertNeverReExecutesADoneTask(dir, "M002", next);
        assert.deepEqual(next, { type: "complete-slice", slice: "S02" });
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    });

    test("scenario 3 — milestone 100% complete (fixture untouched): deriveNextUnit reflects M002-SUMMARY.md's real existence", () => {
      const dir = setupMidFlightFixture("milestone-complete");
      try {
        applyMigration(dir);
        const snap = readSnapshot(dir);

        // The real M002-SUMMARY.md exists in the forge-agent 1.0 fixture
        // (asserted against the real path, not assumed) — so the expected
        // result is `null` (the milestone-close artifact already exists on
        // disk), NOT `complete-milestone`. Documented explicitly per the
        // plan's must_have: if the fixture ever lost that file, this branch
        // flips to asserting `complete-milestone` instead — never hardcoded
        // to one outcome regardless of the real fixture state.
        const milestoneSummaryPath = join(dir, ".gsd", "milestones", "M002", "M002-SUMMARY.md");
        assert.equal(snap.milestoneSummaryWritten, existsSync(milestoneSummaryPath));

        const next = deriveNextUnit(snap.state, snap.roadmap, snap.plans, {
          milestoneSummaryWritten: snap.milestoneSummaryWritten,
        });

        assertNeverReExecutesADoneTask(dir, "M002", next);
        if (snap.milestoneSummaryWritten) {
          assert.equal(next, null, "M002-SUMMARY.md already exists on disk — nothing left to dispatch");
        } else {
          assert.deepEqual(next, { type: "complete-milestone", milestone: "M002" });
        }
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    });
  },
);
