/**
 * Forge migrate — coverage for `state-convert.ts` (S02/T02): the five
 * `StateConvertAction`s (`noop-native`/`noop-absent`/`skip-unknown`/`convert`/
 * `skip-ambiguous`), the `parseFrontmatter1xFields` extractor, the
 * `applyStateConversion` write gate (only `convert` touches disk, via the real
 * `state/store.ts:updateState`), and a real-fixture regression against
 * `~/Documents/dev/forge-agent/.gsd/` (a completed milestone must never be
 * treated as active).
 *
 * Same one-shot-copy / skip-honest discipline as `migrate-memory-convert.test.ts`
 * (T05) and `gsd-history-operation.test.ts`: the live forge-agent 1.0 fixture is
 * read AT MOST once, copied into a `mkdtemp` sandbox, and only the sandbox copy
 * is asserted against. Skips honestly when the fixture is absent from this
 * machine instead of red-falsing.
 */

import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir, homedir } from "node:os";
import { join } from "node:path";
import { computeStateConversion, applyStateConversion, parseFrontmatter1xFields } from "../migrate/state-convert.ts";
import { parseState } from "../state/parse.ts";

function withSandbox<T>(fn: (dir: string) => T): T {
  const dir = mkdtempSync(join(tmpdir(), "forge-migrate-state-convert-test-"));
  try {
    return fn(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function writeDashboard(cwd: string, content: string): string {
  const dir = join(cwd, ".gsd");
  mkdirSync(dir, { recursive: true });
  const path = join(dir, "STATE.md");
  writeFileSync(path, content, "utf-8");
  return path;
}

function writeMilestoneState(cwd: string, milestoneId: string, content: string): void {
  const dir = join(cwd, ".gsd", "milestones", milestoneId);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, `${milestoneId}-STATE.md`), content, "utf-8");
}

const SYNTHETIC_DASHBOARD = [
  "<!-- AUTO-GENERATED by scripts/forge-dashboard.js — do not edit by hand -->",
  "<!-- Last regen: 2026-01-01T00:00:00.000Z -->",
  "",
  "# GSD Dashboard",
  "",
  "No active runs.",
  "",
].join("\n");

function syntheticMilestoneState(opts: {
  milestone: string;
  status: string;
  activeSlice?: string;
  phase?: string;
  nextAction?: string;
}): string {
  return [
    "---",
    `milestone: ${opts.milestone}`,
    "kind: milestone",
    "created: 2026-01-01T00:00:00.000Z",
    "last_updated: 2026-01-02T00:00:00Z",
    "isolation_mode: worktree",
    `status: ${opts.status}`,
    "---",
    "",
    `# ${opts.milestone} State`,
    "",
    `**Active Slice:** ${opts.activeSlice ?? "—"}`,
    "**Active Task:** —",
    `**Phase:** ${opts.phase ?? ""}`,
    "**Auto-mode:** off",
    `**Next Action:** ${opts.nextAction ?? ""}`,
    "",
  ].join("\n");
}

// ── parseFrontmatter1xFields ─────────────────────────────────────────────────

describe("parseFrontmatter1xFields", () => {
  test("extracts milestone/status from frontmatter, phase/activeSlice/nextAction from prose body", () => {
    const raw = syntheticMilestoneState({
      milestone: "M100",
      status: "in_progress",
      activeSlice: "S02",
      phase: "execute",
      nextAction: "Continue T03.",
    });
    const fields = parseFrontmatter1xFields(raw);
    assert.equal(fields.milestone, "M100");
    assert.equal(fields.status, "in_progress");
    assert.equal(fields.activeSlice, "S02");
    assert.equal(fields.phase, "execute");
    assert.equal(fields.nextAction, "Continue T03.");
  });

  test("em-dash (—) Active Slice normalizes to empty string, not the literal em-dash", () => {
    const raw = syntheticMilestoneState({ milestone: "M002", status: "complete" });
    const fields = parseFrontmatter1xFields(raw);
    assert.equal(fields.activeSlice, "");
  });

  test("missing fields degrade to empty strings, never throws", () => {
    const fields = parseFrontmatter1xFields("not even a frontmatter block\n");
    assert.deepEqual(fields, { milestone: "", status: "", phase: "", activeSlice: "", nextAction: "" });
  });
});

// ── computeStateConversion — the five actions (synthetic) ───────────────────

describe("computeStateConversion", () => {
  test("2.0-native fenced yaml with non-empty milestone → noop-native", () => {
    withSandbox((dir) => {
      writeDashboard(dir, "# STATE\n\n```yaml\nmilestone: M900\nphase: execute\n```\n");
      const plan = computeStateConversion(dir);
      assert.equal(plan.action, "noop-native");
      assert.equal(plan.targetDoc, undefined);
    });
  });

  test("absent .gsd/STATE.md → noop-absent", () => {
    withSandbox((dir) => {
      const plan = computeStateConversion(dir);
      assert.equal(plan.action, "noop-absent");
    });
  });

  test("unrecognized content (no dashboard marker, no fenced yaml) → skip-unknown", () => {
    withSandbox((dir) => {
      writeDashboard(dir, "# Random notes\n\nNothing recognizable here.\n");
      const plan = computeStateConversion(dir);
      assert.equal(plan.action, "skip-unknown");
    });
  });

  test("dashboard1x + zero frontmatter1x under milestones/ → convert with empty shell {milestone:\"\"}", () => {
    withSandbox((dir) => {
      writeDashboard(dir, SYNTHETIC_DASHBOARD);
      const plan = computeStateConversion(dir);
      assert.equal(plan.action, "convert");
      assert.deepEqual(plan.targetDoc, { milestone: "" });
    });
  });

  test("dashboard1x + exactly one non-terminal frontmatter1x → convert with filled shell, units never populated", () => {
    withSandbox((dir) => {
      writeDashboard(dir, SYNTHETIC_DASHBOARD);
      writeMilestoneState(dir, "M100", syntheticMilestoneState({
        milestone: "M100",
        status: "active",
        activeSlice: "S02",
        phase: "execute",
        nextAction: "Continue T03.",
      }));

      const plan = computeStateConversion(dir);
      assert.equal(plan.action, "convert");
      assert.equal(plan.targetDoc?.milestone, "M100");
      assert.equal(plan.targetDoc?.phase, "execute");
      assert.equal(plan.targetDoc?.current_slice, "S02");
      assert.equal(plan.targetDoc?.next_action, "Continue T03.");
      assert.equal(plan.targetDoc?.units, undefined);
      assert.ok(!("units" in (plan.targetDoc ?? {})));
    });
  });

  test("dashboard1x + two simultaneously non-terminal frontmatter1x → skip-ambiguous, no write, dashboard byte-identical", () => {
    withSandbox((dir) => {
      const dashboardPath = writeDashboard(dir, SYNTHETIC_DASHBOARD);
      writeMilestoneState(dir, "M100", syntheticMilestoneState({ milestone: "M100", status: "active" }));
      writeMilestoneState(dir, "M200", syntheticMilestoneState({ milestone: "M200", status: "in_progress" }));

      const before = readFileSync(dashboardPath, "utf-8");
      const plan = computeStateConversion(dir);
      assert.equal(plan.action, "skip-ambiguous");
      assert.match(plan.detail, /M100/);
      assert.match(plan.detail, /M200/);

      const result = applyStateConversion(dir);
      assert.equal(result.written, false);
      const after = readFileSync(dashboardPath, "utf-8");
      assert.equal(after, before);
    });
  });
});

// ── applyStateConversion — write gate + real round-trip via updateState/parseState ──

describe("applyStateConversion", () => {
  test("action !== convert never touches disk (noop-native example)", () => {
    withSandbox((dir) => {
      const content = "# STATE\n\n```yaml\nmilestone: M900\n```\n";
      const path = writeDashboard(dir, content);
      const result = applyStateConversion(dir);
      assert.equal(result.written, false);
      assert.equal(readFileSync(path, "utf-8"), content);
    });
  });

  test("action === convert writes via the real updateState, round-trips through the real parseState", () => {
    withSandbox((dir) => {
      writeDashboard(dir, SYNTHETIC_DASHBOARD);
      writeMilestoneState(dir, "M100", syntheticMilestoneState({
        milestone: "M100",
        status: "active",
        activeSlice: "S02",
        phase: "execute",
        nextAction: "Continue T03.",
      }));

      const result = applyStateConversion(dir);
      assert.equal(result.written, true);

      const raw = readFileSync(result.path, "utf-8");
      const reparsed = parseState(raw);
      assert.equal(reparsed.milestone, "M100");
      assert.equal(reparsed.phase, "execute");
      assert.equal(reparsed.current_slice, "S02");
      assert.equal(reparsed.next_action, "Continue T03.");
    });
  });
});

// ── Real fixture: forge-agent 1.0's live STATE.md (dashboard) + a completed milestone ──

const FORGE_AGENT_ROOT = join(homedir(), "Documents", "dev", "forge-agent");
const FORGE_AGENT_STATE = join(FORGE_AGENT_ROOT, ".gsd", "STATE.md");
const FORGE_AGENT_M002_STATE = join(FORGE_AGENT_ROOT, ".gsd", "milestones", "M002", "M002-STATE.md");
const FORGE_AGENT_SKIP =
  "~/Documents/dev/forge-agent não existe nesta máquina — projeto 1.0 separado, fixture só disponível no " +
  "workspace de desenvolvimento que o tem clonado";

describe(
  "computeStateConversion — real fixture (forge-agent 1.0 dashboard + completed M002)",
  { skip: !(existsSync(FORGE_AGENT_STATE) && existsSync(FORGE_AGENT_M002_STATE)) && FORGE_AGENT_SKIP },
  () => {
    test("dashboard 'No active runs' + M002 status:complete → convert with empty shell {milestone:\"\"} (complete milestone never counts as active)", () => {
      let dashboardContent: string;
      let m002Content: string;
      try {
        dashboardContent = readFileSync(FORGE_AGENT_STATE, "utf-8");
        m002Content = readFileSync(FORGE_AGENT_M002_STATE, "utf-8");
      } catch {
        return;
      }

      withSandbox((dir) => {
        writeDashboard(dir, dashboardContent);
        writeMilestoneState(dir, "M002", m002Content);

        const plan = computeStateConversion(dir);
        assert.equal(plan.action, "convert");
        assert.deepEqual(plan.targetDoc, { milestone: "" });
      });
    });
  },
);
