/**
 * Forge migrate — coverage for `classifyStateLayout`/`classifyMilestoneStateLayouts`
 * (T01).
 *
 * Same one-shot-copy discipline as `gsd-history-operation.test.ts`: the live
 * `.gsd/` of THIS repo (gerido pelo 2.0 pós-virada, ver CLAUDE.md) and the live
 * `~/Documents/dev/forge-agent/.gsd/` (projeto 1.0 separado) are each read AT
 * MOST once, copied into a `mkdtemp` sandbox, and only the sandbox copy is
 * asserted against — never the original, never a second read.
 *
 * NOTE (deviation from the literal T01-PLAN fixture claim): T01-PLAN assumed
 * the live top-level `.gsd/STATE.md` of THIS repo still carried the forge 1.0
 * dashboard shape. It no longer does — S08's ceremony (2026-07-10) landed and
 * the 2.0 binary now owns this repo's `.gsd/`, so its top-level STATE.md is
 * genuinely 2.0-native fenced-yaml (verified by hand: `head .gsd/STATE.md`
 * shows a ` ```yaml ` block with `milestone: M-20260710225229-forge-merge`).
 * The real forge-1.0-dashboard fixture now lives at
 * `~/Documents/dev/forge-agent/.gsd/STATE.md` (that project is still on 1.0)
 * — it carries the exact `AUTO-GENERATED by scripts/forge-dashboard.js`
 * marker the plan describes, so it replaces this repo's live file as the real
 * dashboard1x fixture below. This repo's own live file is kept as a bonus
 * real-data case asserting `twoPointZero`, which is arguably a better proof
 * point: it confirms the classifier correctly reads genuine 2.0-native output
 * the binary just wrote, not just synthetic strings.
 */

import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir, homedir } from "node:os";
import { join } from "node:path";
import { classifyStateLayout, classifyMilestoneStateLayouts } from "../migrate/state-layout.ts";

function withSandbox<T>(fn: (dir: string) => T): T {
  const dir = mkdtempSync(join(tmpdir(), "forge-migrate-state-layout-test-"));
  try {
    return fn(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function writeGsdState(cwd: string, content: string): void {
  const gsdDir = join(cwd, ".gsd");
  mkdirSync(gsdDir, { recursive: true });
  writeFileSync(join(gsdDir, "STATE.md"), content);
}

function writeMilestoneState(cwd: string, milestoneId: string, fileName: string, content: string): void {
  const dir = join(cwd, ".gsd", "milestones", milestoneId);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, fileName), content);
}

// ── classifyStateLayout — synthetic ──────────────────────────────────────────

describe("classifyStateLayout — synthetic", () => {
  test("absent — no .gsd/STATE.md at all", () => {
    withSandbox((dir) => {
      const finding = classifyStateLayout(dir);
      assert.equal(finding.kind, "absent");
      assert.ok(finding.detail.length > 0);
    });
  });

  test("twoPointZero — fenced ```yaml block with non-empty milestone", () => {
    withSandbox((dir) => {
      writeGsdState(
        dir,
        ["# STATE", "", "```yaml", "milestone: teste", "phase: executing", "```", ""].join("\n"),
      );
      const finding = classifyStateLayout(dir);
      assert.equal(finding.kind, "twoPointZero");
    });
  });

  test("dashboard1x — synthetic AUTO-GENERATED marker, no fenced yaml", () => {
    withSandbox((dir) => {
      writeGsdState(
        dir,
        [
          "<!-- AUTO-GENERATED by scripts/forge-dashboard.js — do not edit by hand -->",
          "<!-- Last regen: 2026-07-08T17:51:27.076Z -->",
          "",
          "# GSD Dashboard",
          "",
          "No active runs.",
          "Last completed: M001 — algo qualquer.",
          "",
        ].join("\n"),
      );
      const finding = classifyStateLayout(dir);
      assert.equal(finding.kind, "dashboard1x");
    });
  });

  test("unknown — content matches none of the known shapes, never throws", () => {
    withSandbox((dir) => {
      writeGsdState(dir, "algo completamente aleatório sem forma reconhecível\n");
      const finding = classifyStateLayout(dir);
      assert.equal(finding.kind, "unknown");
    });
  });
});

// ── classifyMilestoneStateLayouts — synthetic ────────────────────────────────

describe("classifyMilestoneStateLayouts — synthetic", () => {
  test("missing .gsd/milestones/ → [] (never throws)", () => {
    withSandbox((dir) => {
      const findings = classifyMilestoneStateLayouts(dir);
      assert.deepEqual(findings, []);
    });
  });

  test("frontmatter1x — long-form `<mid>-STATE.md` name", () => {
    withSandbox((dir) => {
      writeMilestoneState(
        dir,
        "M999",
        "M999-STATE.md",
        [
          "---",
          "milestone: M999",
          "kind: milestone",
          "status: complete",
          "---",
          "",
          "# M999 State",
          "",
          "**Active Slice:** —",
          "**Active Task:** —",
          "",
        ].join("\n"),
      );
      const findings = classifyMilestoneStateLayouts(dir);
      assert.equal(findings.length, 1);
      assert.equal(findings[0].kind, "frontmatter1x");
      assert.ok(findings[0].path.endsWith(join("M999", "M999-STATE.md")));
    });
  });

  test("frontmatter1x — short-form `STATE.md` name", () => {
    withSandbox((dir) => {
      writeMilestoneState(
        dir,
        "M998",
        "STATE.md",
        ["---", "milestone: M998", "---", "", "**Active Slice:** S01", ""].join("\n"),
      );
      const findings = classifyMilestoneStateLayouts(dir);
      assert.equal(findings.length, 1);
      assert.equal(findings[0].kind, "frontmatter1x");
      assert.ok(findings[0].path.endsWith(join("M998", "STATE.md")));
    });
  });

  test("unknown — milestone dir has a STATE file that matches neither shape", () => {
    withSandbox((dir) => {
      writeMilestoneState(dir, "M997", "M997-STATE.md", "conteúdo sem frontmatter nem Active Slice\n");
      const findings = classifyMilestoneStateLayouts(dir);
      assert.equal(findings.length, 1);
      assert.equal(findings[0].kind, "unknown");
    });
  });

  test("milestone dir with no STATE file at all is skipped, not reported", () => {
    withSandbox((dir) => {
      const dir996 = join(dir, ".gsd", "milestones", "M996");
      mkdirSync(dir996, { recursive: true });
      writeFileSync(join(dir996, "M996-ROADMAP.md"), "# roadmap\n");
      const findings = classifyMilestoneStateLayouts(dir);
      assert.equal(findings.length, 0);
    });
  });
});

// ── Real fixture 1: forge-agent 1.0's live top-level dashboard STATE.md ──────

const FORGE_AGENT_ROOT = join(homedir(), "Documents", "dev", "forge-agent");
const FORGE_AGENT_STATE = join(FORGE_AGENT_ROOT, ".gsd", "STATE.md");
const FORGE_AGENT_M002_STATE = join(FORGE_AGENT_ROOT, ".gsd", "milestones", "M002", "M002-STATE.md");

const FORGE_AGENT_SKIP =
  "~/Documents/dev/forge-agent não existe nesta máquina — projeto 1.0 separado, " +
  "fixture só disponível no workspace de desenvolvimento que o tem clonado";

describe("classifyStateLayout — real fixture (forge-agent 1.0 live dashboard)", {
  skip: !existsSync(FORGE_AGENT_STATE) && FORGE_AGENT_SKIP,
}, () => {
  test("one-shot copy of ~/Documents/dev/forge-agent/.gsd/STATE.md classifies as dashboard1x", () => {
    let liveContent: string;
    try {
      liveContent = readFileSync(FORGE_AGENT_STATE, "utf-8");
    } catch {
      return; // race with the skip guard above — bail out honestly, no assertion
    }

    withSandbox((dir) => {
      writeGsdState(dir, liveContent);
      const finding = classifyStateLayout(dir);
      assert.equal(finding.kind, "dashboard1x");
    });
  });
});

// ── Real fixture 2: forge-agent 1.0's per-milestone frontmatter STATE.md ────

describe("classifyMilestoneStateLayouts — real fixture (forge-agent 1.0 M002)", {
  skip: !existsSync(FORGE_AGENT_M002_STATE) && FORGE_AGENT_SKIP,
}, () => {
  test("one-shot copy of ~/Documents/dev/forge-agent/.gsd/milestones/M002/M002-STATE.md classifies as frontmatter1x", () => {
    let liveContent: string;
    try {
      liveContent = readFileSync(FORGE_AGENT_M002_STATE, "utf-8");
    } catch {
      return;
    }

    withSandbox((dir) => {
      writeMilestoneState(dir, "M002", "M002-STATE.md", liveContent);
      const findings = classifyMilestoneStateLayouts(dir);
      const m002 = findings.find((f) => f.path.endsWith(join("M002", "M002-STATE.md")));
      assert.ok(m002, "expected a finding for M002-STATE.md");
      assert.equal(m002!.kind, "frontmatter1x");
    });
  });
});

// ── Bonus real-data case: THIS repo's live top-level STATE.md ───────────────
//
// Post-virada (2026-07-10) this repo's own .gsd/STATE.md is genuinely
// 2.0-native (the 2.0 binary now writes it) — see the file-level NOTE above.
// Structural-only, one-shot copy, same discipline as gsd-history-operation.test.ts.

describe("classifyStateLayout — real fixture (this repo's live post-virada STATE.md)", () => {
  test("one-shot copy of this repo's .gsd/STATE.md classifies as twoPointZero", () => {
    let liveContent: string;
    try {
      liveContent = readFileSync(join(process.cwd(), ".gsd", "STATE.md"), "utf-8");
    } catch {
      return; // fresh clone / no live .gsd — nothing to assert here
    }

    withSandbox((dir) => {
      writeGsdState(dir, liveContent);
      const finding = classifyStateLayout(dir);
      assert.equal(finding.kind, "twoPointZero");
    });
  });
});
