/**
 * Forge migrate — coverage for `apply.ts` (S02/T06): the `--apply`
 * orchestrator. Proves the HARD RULE (ROADMAP, incident 2026-06-10 of the
 * real 1.0) end-to-end: `backupGsdTree` (T01) runs exactly once, always
 * BEFORE any of the four `applyX` converters (T02-T05), and only when
 * `buildMigrateReport` (S01) shows something genuinely needs converting.
 *
 * Same isolated-home discipline as `migrate-prefs-convert.test.ts` — `HOME`/
 * `FORGE_HOME` are sandboxed so a real machine's `~/.claude/forge-agent-
 * prefs.md`/`gsdHome()/prefs.md` never contaminates these cases (prefs is one
 * of the four dimensions `applyMigration` decides on).
 */

import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync, statSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { applyMigration, formatApplyReport, type ApplyReport } from "../migrate/apply.ts";

function withIsolatedHome<T>(fn: (fakeHome: string) => T): T {
  const fakeHome = mkdtempSync(join(tmpdir(), "forge-migrate-apply-home-"));
  const prevHome = process.env.HOME;
  const prevForgeHome = process.env.FORGE_HOME;
  process.env.HOME = fakeHome;
  process.env.FORGE_HOME = join(fakeHome, ".forge");
  try {
    return fn(fakeHome);
  } finally {
    if (prevHome === undefined) delete process.env.HOME;
    else process.env.HOME = prevHome;
    if (prevForgeHome === undefined) delete process.env.FORGE_HOME;
    else process.env.FORGE_HOME = prevForgeHome;
    rmSync(fakeHome, { recursive: true, force: true });
  }
}

function withSandbox<T>(fn: (dir: string) => T): T {
  const dir = mkdtempSync(join(tmpdir(), "forge-migrate-apply-test-"));
  try {
    return fn(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function withIsolatedHomeAndSandbox<T>(fn: (dir: string) => T): T {
  return withIsolatedHome(() => withSandbox(fn));
}

function backupDirsIn(dir: string): string[] {
  return readdirSync(dir).filter((name) => name.startsWith(".gsd-backup-"));
}

function snapshotTree(root: string): string[] {
  const out: string[] = [];
  function walk(dir: string): void {
    for (const name of readdirSync(dir).sort()) {
      const full = join(dir, name);
      const st = statSync(full);
      if (st.isDirectory()) {
        walk(full);
      } else {
        out.push(`${full.slice(root.length)}:${st.size}:${readFileSync(full, "utf-8")}`);
      }
    }
  }
  walk(root);
  return out;
}

function writeNativeGsdFixture(cwd: string): void {
  const gsdDir = join(cwd, ".gsd");
  mkdirSync(gsdDir, { recursive: true });
  writeFileSync(join(gsdDir, "STATE.md"), "# STATE\n\n```yaml\nmilestone: M900\n```\n");
}

function writeMixedGsdFixture(cwd: string): void {
  const gsdDir = join(cwd, ".gsd");
  mkdirSync(gsdDir, { recursive: true });
  writeFileSync(
    join(gsdDir, "STATE.md"),
    [
      "<!-- AUTO-GENERATED by scripts/forge-dashboard.js — do not edit by hand -->",
      "",
      "# GSD Dashboard",
      "",
      "No active runs.",
      "",
    ].join("\n"),
  );

  const decisionsDir = join(gsdDir, "decisions");
  mkdirSync(decisionsDir, { recursive: true });
  writeFileSync(
    join(decisionsDir, "M001.md"),
    [
      "---",
      "unit_id: M001",
      "decisions:",
      "  - when: 2026-01-01",
      "    scope: teste",
      "    decision: algo",
      "    choice: A",
      "    rationale: porque sim",
      "    revisable: true",
      "---",
      "",
    ].join("\n"),
  );
}

function writeMilestoneWithProse1xRoadmap(cwd: string, milestoneId: string): void {
  const milestoneDir = join(cwd, ".gsd", "milestones", milestoneId);
  mkdirSync(milestoneDir, { recursive: true });

  writeFileSync(
    join(milestoneDir, `${milestoneId}-STATE.md`),
    [
      "---",
      `milestone: ${milestoneId}`,
      "kind: milestone",
      "created: 2026-01-01T00:00:00.000Z",
      "last_updated: 2026-01-02T00:00:00Z",
      "isolation_mode: worktree",
      "status: active",
      "---",
      "",
      `# ${milestoneId} State`,
      "",
      "**Active Slice:** S01",
      "**Active Task:** —",
      "**Phase:** execute",
      "**Auto-mode:** off",
      "**Next Action:** Continue S01.",
      "",
    ].join("\n"),
  );

  writeFileSync(
    join(milestoneDir, `${milestoneId}-ROADMAP.md`),
    [
      "---",
      `milestone: ${milestoneId}`,
      "---",
      "",
      `# ${milestoneId} ROADMAP`,
      "",
      "## Slices",
      "",
      "- [x] **S01: Slice um** `risk:low` `depends:[]`",
      "",
      "## Notes",
      "",
      "Nada.",
      "",
    ].join("\n"),
  );
}

// ── Empty sandbox — no .gsd/ at all ─────────────────────────────────────────

describe("applyMigration — empty sandbox (no .gsd/ at all)", () => {
  test("returns backup: null, every sub-result empty/no-op, creates nothing on disk", () => {
    withIsolatedHomeAndSandbox((dir) => {
      const before = readdirSync(dir);
      const report = applyMigration(dir);

      assert.equal(report.backup, null);
      assert.equal(report.state.written, false);
      assert.deepEqual(report.prefs, []);
      assert.deepEqual(report.decisions, []);
      assert.deepEqual(report.memory, []);

      const after = readdirSync(dir);
      assert.deepEqual(after, before, "zero-write: sandbox root must be unchanged");
      assert.equal(existsSync(join(dir, ".gsd")), false, "no .gsd/ should have been created");
      assert.deepEqual(backupDirsIn(dir), []);
    });
  });
});

// ── 2.0-native .gsd/ — nothing needs converting ─────────────────────────────

describe("applyMigration — .gsd/ already 2.0-native (fenced STATE.md, no nested prefs, no incompatible fragments)", () => {
  test("returns backup: null, no .gsd-backup-* created, .gsd/ untouched", () => {
    withIsolatedHomeAndSandbox((dir) => {
      writeNativeGsdFixture(dir);
      const before = snapshotTree(join(dir, ".gsd"));

      const report = applyMigration(dir);

      assert.equal(report.backup, null);
      assert.deepEqual(backupDirsIn(dir), []);

      const after = snapshotTree(join(dir, ".gsd"));
      assert.deepEqual(after, before, ".gsd/ tree must be byte-identical — nothing needed converting");
    });
  });
});

// ── Mixed .gsd/ — something needs converting ────────────────────────────────

describe("applyMigration — mixed .gsd/ (dashboard1x STATE.md + a 1.0-shaped decisions fragment)", () => {
  test("backs up .gsd/ exactly once, backup content matches the PRE-conversion snapshot byte-for-byte, and STATE.md is rewritten", () => {
    withIsolatedHomeAndSandbox((dir) => {
      writeMixedGsdFixture(dir);
      const preConversionSnapshot = snapshotTree(join(dir, ".gsd"));

      const report = applyMigration(dir);

      assert.ok(report.backup, "expected a backup to have been created");
      const backupDirs = backupDirsIn(dir);
      assert.equal(backupDirs.length, 1, "exactly one backup dir per --apply invocation");
      assert.equal(report.backup!.dir, join(dir, backupDirs[0]));

      const backupSnapshot = snapshotTree(report.backup!.dir);
      assert.deepEqual(
        backupSnapshot,
        preConversionSnapshot,
        "backup content must match the .gsd/ tree exactly as it was BEFORE any applyX ran",
      );

      const postConversionStateRaw = readFileSync(join(dir, ".gsd", "STATE.md"), "utf-8");
      const preConversionStateRaw = readFileSync(join(report.backup!.dir, "STATE.md"), "utf-8");
      assert.notEqual(
        postConversionStateRaw,
        preConversionStateRaw,
        ".gsd/STATE.md must have been rewritten post-apply, unlike the pristine pre-conversion backup copy",
      );
      assert.equal(report.state.written, true);
      assert.match(postConversionStateRaw, /```yaml/, "post-apply STATE.md should now be the 2.0 fenced-yaml shell");

      assert.equal(report.decisions.length, 1);
      assert.equal(report.decisions[0].path, join(dir, ".gsd", "decisions", "M001.md"));
    });
  });

  test("re-reading the converted decisions fragment from disk shows the 2.0 shape (id/decision/rationale/date)", () => {
    withIsolatedHomeAndSandbox((dir) => {
      writeMixedGsdFixture(dir);
      applyMigration(dir);

      const raw = readFileSync(join(dir, ".gsd", "decisions", "M001.md"), "utf-8");
      assert.match(raw, /id:\s*M001-D1/);
      assert.match(raw, /date:\s*2026-01-01/);
    });
  });
});

// ── Roadmap + units orchestration (S03/T04) ─────────────────────────────────

describe("applyMigration — roadmap + units orchestration (S03/T04)", () => {
  test("resolves the winner milestoneId from state conversion and chains applyRoadmapConversion + applyUnitsConversion", () => {
    withIsolatedHomeAndSandbox((dir) => {
      writeMixedGsdFixture(dir);
      writeMilestoneWithProse1xRoadmap(dir, "M100");

      const report = applyMigration(dir);

      assert.equal(report.state.written, true);
      assert.equal(report.state.milestoneId, "M100");

      assert.equal(report.roadmap.written, true, "prose1x ROADMAP.md should have been converted");
      const roadmapRaw = readFileSync(join(dir, ".gsd", "milestones", "M100", "M100-ROADMAP.md"), "utf-8");
      assert.match(roadmapRaw, /\| ID \| Nome \| Risk \| Depends \| Status \|/, "ROADMAP.md must now hold the 2.0 pipe table");
      assert.match(roadmapRaw, /\| S01 \|/);

      assert.equal(report.units.written, true, "units[] must be populated from the ORIGINAL prose1x roadmap, not the post-conversion pipe table");
      assert.equal(report.units.unitCount, 1, "one slice unit (S01), no tasks on disk");
      assert.deepEqual(report.units.warnings, []);
    });
  });

  test("skip-ambiguous (0 or 2+ active milestones) never calls applyRoadmapConversion/applyUnitsConversion — no milestoneId to pass them", () => {
    withIsolatedHomeAndSandbox((dir) => {
      writeMixedGsdFixture(dir);
      writeMilestoneWithProse1xRoadmap(dir, "M100");
      writeMilestoneWithProse1xRoadmap(dir, "M200");

      const roadmapBefore = readFileSync(join(dir, ".gsd", "milestones", "M100", "M100-ROADMAP.md"), "utf-8");

      const report = applyMigration(dir);

      assert.equal(report.state.written, false);
      assert.equal(report.state.milestoneId, undefined);
      assert.equal(report.roadmap.written, false);
      assert.equal(report.units.written, false);
      assert.equal(report.units.unitCount, 0);

      const roadmapAfter = readFileSync(join(dir, ".gsd", "milestones", "M100", "M100-ROADMAP.md"), "utf-8");
      assert.equal(roadmapAfter, roadmapBefore, "ambiguity gate must leave the prose1x ROADMAP.md untouched");
    });
  });
});

// ── formatApplyReport ────────────────────────────────────────────────────────

describe("formatApplyReport", () => {
  const baseReport: ApplyReport = {
    backup: null,
    state: { written: false, path: "/tmp/fixture/.gsd/STATE.md", detail: "nada precisava de conversão — pulado" },
    prefs: [],
    decisions: [],
    memory: [],
    roadmap: { written: false, path: "", detail: "sem milestone ativo resolvido — pulado" },
    units: { written: false, unitCount: 0, warnings: [] },
    warnings: [],
  };

  test("with backup filled: mentions the backup dir and a rollback instruction", () => {
    const report: ApplyReport = { ...baseReport, backup: { dir: "/tmp/fixture/.gsd-backup-xyz", fileCount: 3 } };
    const text = formatApplyReport(report);
    assert.match(text, /\/tmp\/fixture\/\.gsd-backup-xyz/);
    assert.match(text, /reverter/i);
    assert.match(text, /\.gsd\//);
  });

  test("with backup: null, mentions that no backup was needed", () => {
    const text = formatApplyReport(baseReport);
    assert.match(text, /nenhum backup/i);
  });
});
