/**
 * Forge migrate — STATE.md layout classifier.
 *
 * `forge migrate` (T04) needs to know, for a given `cwd`, which physical shape
 * of `STATE.md` it is looking at before it can decide what to do with it:
 *   - the 2.0-native fenced-```yaml block (state/parse.ts already reads this)
 *   - the forge 1.0 top-level dashboard (auto-generated by
 *     scripts/forge-dashboard.js, prose-only, no fenced yaml)
 *   - the forge 1.0 per-milestone frontmatter (`---\nmilestone: ...\n---` +
 *     `**Active Slice:**` prose body)
 *   - absent, or a shape none of the above recognize
 *
 * This module only classifies — it never writes, never mutates, and never
 * throws (a migration dry-run must survive a directory tree it doesn't fully
 * understand).
 *
 * Pure module: node builtins only, no `@gsd/*` runtime import.
 */

import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { parseState } from "../state/parse.js";

export type StateLayoutKind = "absent" | "twoPointZero" | "dashboard1x" | "frontmatter1x" | "unknown";

export interface StateLayoutFinding {
  kind: StateLayoutKind;
  path: string;
  detail: string;
}

const DASHBOARD_MARKER = "AUTO-GENERATED by scripts/forge-dashboard.js";

/**
 * Classify `<cwd>/.gsd/STATE.md` (the top-level state artifact).
 *
 * Order of checks matters: the 2.0 fenced-yaml shape is checked first (via
 * the SAME regex `parseState` uses, by delegating to it rather than
 * duplicating the pattern), then the 1.0 dashboard marker, then unknown.
 */
export function classifyStateLayout(cwd: string): StateLayoutFinding {
  const path = join(cwd, ".gsd", "STATE.md");

  if (!existsSync(path)) {
    return { kind: "absent", path, detail: "não existe .gsd/STATE.md neste diretório" };
  }

  const content = readFileSync(path, "utf-8");

  const parsed = parseState(content);
  if (parsed.milestone.trim() !== "") {
    return {
      kind: "twoPointZero",
      path,
      detail: "bloco fenced ```yaml com `milestone:` não-vazio (formato 2.0-nativo)",
    };
  }

  if (content.includes(DASHBOARD_MARKER)) {
    return {
      kind: "dashboard1x",
      path,
      detail: "comentário HTML AUTO-GENERATED by scripts/forge-dashboard.js (dashboard forge 1.0)",
    };
  }

  return { kind: "unknown", path, detail: "conteúdo não bate nenhum padrão conhecido de STATE.md" };
}

const FRONTMATTER_BLOCK = /^---\n[\s\S]*?\n---/;
const ACTIVE_SLICE_MARKER = "**Active Slice:**";

function findMilestoneStateFile(milestoneDir: string, entryName: string): string | null {
  const longForm = join(milestoneDir, `${entryName}-STATE.md`);
  if (existsSync(longForm)) return longForm;

  const shortForm = join(milestoneDir, "STATE.md");
  if (existsSync(shortForm)) return shortForm;

  return null;
}

/**
 * Classify every per-milestone `STATE.md` under `<cwd>/.gsd/milestones` —
 * the forge 1.0 layout keeps one `<mid>-STATE.md` (or `STATE.md`) per
 * milestone directory, distinct from the single top-level artifact
 * `classifyStateLayout` reads.
 *
 * Missing `.gsd/milestones/` (or an unreadable entry) never throws — it
 * degrades to `[]` / skips that entry, since a migration dry-run must survive
 * a partially-formed or absent `.gsd/` tree.
 */
export function classifyMilestoneStateLayouts(cwd: string): StateLayoutFinding[] {
  const milestonesRoot = join(cwd, ".gsd", "milestones");
  if (!existsSync(milestonesRoot)) return [];

  let entries: string[];
  try {
    entries = readdirSync(milestonesRoot);
  } catch {
    return [];
  }

  const findings: StateLayoutFinding[] = [];

  for (const entryName of entries) {
    const milestoneDir = join(milestonesRoot, entryName);
    let isDir: boolean;
    try {
      isDir = statSync(milestoneDir).isDirectory();
    } catch {
      continue;
    }
    if (!isDir) continue;

    const statePath = findMilestoneStateFile(milestoneDir, entryName);
    if (!statePath) continue;

    let content: string;
    try {
      content = readFileSync(statePath, "utf-8");
    } catch {
      continue;
    }

    if (FRONTMATTER_BLOCK.test(content) && content.includes(ACTIVE_SLICE_MARKER)) {
      findings.push({
        kind: "frontmatter1x",
        path: statePath,
        detail: "frontmatter --- + **Active Slice:** no corpo (per-milestone STATE forge 1.0)",
      });
    } else {
      findings.push({
        kind: "unknown",
        path: statePath,
        detail: "conteúdo não bate o padrão frontmatter 1.0 per-milestone",
      });
    }
  }

  return findings;
}
